Updated from dropbox API v1 to v2
alces-software/clusterware-dropbox-cli pull request #1
Opened 2017-05-03 13:04 UTC by WilliamMcCumstie

Removed the old ruby dropbox gem and replaced it with a new gem using v2. Note that the new dropbox gem version number is currently 0.1.5 so the code is not as clean as it use to be. Some of the functionality has had minor changes has no direct replacement was available. 

Comparing the v1 and v2 functionality. Differences to be listed as comments

2017-05-03 13:06 UTC, WilliamMcCumstie commented
alces storage: help, enable, forget, use, show, avail are unchanged

2017-05-03 13:10 UTC, WilliamMcCumstie commented
`alces storage configure`:

Minor change. In `v2` updates to OAuth2. The user is now required to follow the link to obtain an access token. This token then needs to be supplied to `alces storage`.

Previously the user only needed to follow the link and then press enter in `alces storage`

2017-05-03 14:37 UTC, WilliamMcCumstie commented
`alces storage put`

Minor changes: 
1. Now shows an upload meter for each file (can be reverted)
1. Minor changes in error messages (possible reverted - doesn't make a huge difference)
1. Previously could not overwrite files with a new file but could overwrite a file with a folder. Can no longer overwrite a file with a folder.
1. Can now upload into a folder that already exists as long as no files conflict. Previously the folder itself would raiser a conflict
1. Prints all files that cause a conflict, not just the first one it finds. 
1. Checks for file conflicts before any files are uploaded instead of as the files are uploaded

Backend change: Uploads on a separate thread and manually implements the session upload. The new sdk does not have helper function to manage the session for you

TODO:
Fix error message when folder tries to replace a file. Error message incoherent

2017-05-03 14:57 UTC, WilliamMcCumstie commented
`alces storage get`

Changes:
1. Can now download empty files
1. Updated error message. Tells users to use `-r` if required
1. Downloads empty folders

NOTE:
An inconsistency exists with `alces storage put`. If a folder exists in the local directory and dropbox, `get` will still throw an error even if the files do not clash where as `put` does not. Possible feature improvement?

2017-05-03 15:02 UTC, WilliamMcCumstie commented
'alces storage list'

Change:
1. No longer displays date for folders, this data is no longer returned by the api

TODO:
1. list root dir if no path input included
1. Fix error message if not found, incoherent

2017-05-03 15:06 UTC, WilliamMcCumstie commented
`alces storage mkbucket`

Change:
1. removed bad OAuth error message when a name conflict occurs - is not an Auth error

TODO:
1. Fix error message in case of conflict, incoherent

2017-05-03 15:12 UTC, WilliamMcCumstie commented
`alces storage rmbucket`

TODO:
1. Prevent it from deleting non-folder objects

NOTE:
1. Both versions will recursively delete by default without a warning
1. Both versions can delete folders not in the root directory even though the `help` page says they can't. Possible future fix?

2017-05-03 15:18 UTC, WilliamMcCumstie commented
`alces storage rm`

Change:
1. Some error messages have changed
1. No longer displays all files deleted recursively, only the folder that has been deleted

2017-05-03 16:47 UTC, WilliamMcCumstie commented
Made the TODO changes

2017-05-03 17:03 UTC, WilliamMcCumstie commented
Made the TODO changes

2017-05-04 09:38 UTC, mjtko requested changes
Nothing major, couple of niggles! :)

2017-05-04 09:38 UTC, mjtko commented on Gemfile
> +# =>
This looks like accidental garbage. :)

2017-05-04 09:38 UTC, mjtko commented on lib/alces/clusterware-dropbox/cli.rb
> +        program :version, '1.1.0'
Given the major changes, might as well bump this to 2.0.0 I think!

2017-05-04 09:38 UTC, mjtko commented on lib/alces/clusterware-dropbox/handler.rb
> +        Dotenv.load(File.expand_path("#{ENV['cw_ROOT']}/opt/clusterware-dropbox-cli/.env"))
Why has this been relocated from its previous location of https://github.com/alces-software/clusterware-dropbox-cli/pull/1/files#diff-27868ef7fd87e8006ab21854cad0e461L32 ?

2017-05-04 09:38 UTC, mjtko commented on lib/alces/clusterware-dropbox/handler.rb
> +        Dotenv.load(File.expand_path("#{ENV['cw_ROOT']}/opt/clusterware-dropbox-cli/.env"))
If these variables are only used during authorization, it might even be better to move this to `#authorize`.

2017-05-04 10:12 UTC, WilliamMcCumstie commented on lib/alces/clusterware-dropbox/handler.rb
> +        Dotenv.load(File.expand_path("#{ENV['cw_ROOT']}/opt/clusterware-dropbox-cli/.env"))
Turns out it was loading the app keys and not the access token. Moved it to Auth

2017-05-04 10:12 UTC, WilliamMcCumstie commented
Changes made

2017-05-04 10:40 UTC, mjtko approved these changes

2017-05-04 10:41 UTC, merged